from pynput.keyboard import Key


class Keys:
    characters = [
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "\\",
        "`",
        "~",
        "!",
        "@",
        "#",
        "$",
        "%",
        "^",
        "&",
        "/",
        "*",
        "(",
        ")",
        "[",
        "]",
        "{",
        "}",
        "<",
        ">",
        "|",
        ";",
        ":",
        "'",
        "\"",
        "?",
        ".",
        "",
        "-",
        "_",
        "+",
        "="
    ]

    non_characters = [
        "Ctrl",
        "Right Ctrl",
        "Shift",
        "Right Shift",
        "Alt",
        "Right Alt",
        "Command",
        "Right Command",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "Escape",
        "Space",
        "BackSpace",
        "Tab",
        "Return",
        "Pause",
        "Scroll_Lock",
        "Delete",
        "Home",
        "Left",
        "Up",
        "Right",
        "Down",
        "Page_Up",
        "Page_Down",
        "End",
        "Insert",
        "Num_Lock",
        "Caps_Lock"
    ]

    modifier_keys = [
        "shift",
        "alt",
        "ctrl",
        "command"
    ]

    keyboard_to_pynput = {
        "Ctrl": Key.ctrl_l,
        "right Ctrl": Key.ctrl_r,
        "Shift": Key.shift_l,
        "right Shift": Key.shift_r,
        "Alt": Key.alt_l,
        "right Alt": Key.alt_r,
        "Command": Key.cmd_l,
        "right Command": Key.cmd_r,
        "F1": Key.f1,
        "F2": Key.f2,
        "F3": Key.f3,
        "F4": Key.f4,
        "F5": Key.f5,
        "F6": Key.f6,
        "F7": Key.f7,
        "F8": Key.f8,
        "F9": Key.f9,
        "F10": Key.f10,
        "F11": Key.f11,
        "F12": Key.f12,
        "Escape": Key.esc,
        "Space": Key.space,
        "BackSpace": Key.backspace,
        "Tab": Key.tab,
        "Return": Key.enter,
        "Pause": Key.pause,
        "Scroll_Lock": Key.scroll_lock,
        "Delete": Key.delete,
        "Home": Key.home,
        "Left": Key.left,
        "Up": Key.up,
        "Right": Key.right,
        "Down": Key.down,
        "Page_Up": Key.page_up,
        "Page_Down": Key.page_down,
        "End": Key.end,
        "Insert": Key.insert,
        "Num_Lock": Key.num_lock,
        "Caps_Lock": Key.caps_lock
    }
